--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: adoption; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.adoption (
    adoptionownerid integer,
    adoptionanimalid integer
);


ALTER TABLE public.adoption OWNER TO postgres;

--
-- Name: animalphotos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.animalphotos (
    photoid integer NOT NULL,
    animalid integer,
    photopath character varying(255) NOT NULL,
    description character varying(255),
    photo_id integer NOT NULL
);


ALTER TABLE public.animalphotos OWNER TO postgres;

--
-- Name: animalphotos_photo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.animalphotos ALTER COLUMN photo_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.animalphotos_photo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: animalphotos_photoid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.animalphotos_photoid_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.animalphotos_photoid_seq OWNER TO postgres;

--
-- Name: animalphotos_photoid_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.animalphotos_photoid_seq OWNED BY public.animalphotos.photoid;


--
-- Name: animals; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.animals (
    animalid integer NOT NULL,
    ownerid integer,
    animaltype character varying(255),
    animalname character varying(255),
    animalage integer,
    animaltimeinshelter integer,
    animalfur character varying(255),
    animalsize character varying(255)
);


ALTER TABLE public.animals OWNER TO postgres;

--
-- Name: animals_animalid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.animals ALTER COLUMN animalid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.animals_animalid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: persons_personid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.persons_personid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.persons_personid_seq OWNER TO postgres;

--
-- Name: persons; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.persons (
    personid integer DEFAULT nextval('public.persons_personid_seq'::regclass) NOT NULL,
    lastname character varying(255),
    firstname character varying(255),
    address character varying(255),
    city character varying(255),
    mail character varying(255),
    phonenumber character varying(255)
);


ALTER TABLE public.persons OWNER TO postgres;

--
-- Name: animalphotos photoid; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.animalphotos ALTER COLUMN photoid SET DEFAULT nextval('public.animalphotos_photoid_seq'::regclass);


--
-- Data for Name: adoption; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.adoption (adoptionownerid, adoptionanimalid) FROM stdin;
\.


--
-- Data for Name: animalphotos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.animalphotos (photoid, animalid, photopath, description, photo_id) FROM stdin;
\.


--
-- Data for Name: animals; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.animals (animalid, ownerid, animaltype, animalname, animalage, animaltimeinshelter, animalfur, animalsize) FROM stdin;
\.


--
-- Data for Name: persons; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.persons (personid, lastname, firstname, address, city, mail, phonenumber) FROM stdin;
1	Kowalski	Jan	ul. Przykładowa 1	Warszawa	jan.kowalski@example.com	123456789
\.


--
-- Name: animalphotos_photo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.animalphotos_photo_id_seq', 1, false);


--
-- Name: animalphotos_photoid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.animalphotos_photoid_seq', 1, false);


--
-- Name: animals_animalid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.animals_animalid_seq', 1, false);


--
-- Name: persons_personid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.persons_personid_seq', 1, true);


--
-- Name: animalphotos animalphotos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.animalphotos
    ADD CONSTRAINT animalphotos_pkey PRIMARY KEY (photoid);


--
-- Name: animals animals_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.animals
    ADD CONSTRAINT animals_pkey PRIMARY KEY (animalid);


--
-- Name: persons persons_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.persons
    ADD CONSTRAINT persons_pkey PRIMARY KEY (personid);


--
-- Name: adoption adoption_adoptionanimalid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.adoption
    ADD CONSTRAINT adoption_adoptionanimalid_fkey FOREIGN KEY (adoptionanimalid) REFERENCES public.animals(animalid);


--
-- Name: adoption adoption_adoptionownerid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.adoption
    ADD CONSTRAINT adoption_adoptionownerid_fkey FOREIGN KEY (adoptionownerid) REFERENCES public.persons(personid);


--
-- Name: animalphotos animalphotos_animalid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.animalphotos
    ADD CONSTRAINT animalphotos_animalid_fkey FOREIGN KEY (animalid) REFERENCES public.animals(animalid) ON DELETE CASCADE;


--
-- Name: animals animals_ownerid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.animals
    ADD CONSTRAINT animals_ownerid_fkey FOREIGN KEY (ownerid) REFERENCES public.persons(personid);


--
-- PostgreSQL database dump complete
--

